SiteLanches/Models/Lanche.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SiteLanches.Models
{
    public class Lanche
    {
        public int LancheId { get; set; }

        [StringLength(100)]
        public string Nome { get; set; }

        [StringLength(100)]
        public string DescricaoCurta { get; set; }

        [StringLength(255)]
        public string DescricaoLonga { get; set; }

        [Column(TypeName = "decimal(18,2)")]
        public decimal Preco { get; set; }

        [StringLength(200)]
        public string ImagemUrl { get; set; }

        [StringLength(200)]
        public string ImagemThumbnailUrl { get; set; }

        public bool IsLanchePreferido { get; set; }
        public bool IsEmEstoque { get; set; }
        public int CategoriaId { get; set; }
        public virtual Categoria Categoria { get; set; }
    }
}

SiteLanches/Controllers/CarrinhoCompraController.cs
using Microsoft.AspNetCore.Mvc;
using SiteLanches.Models;
using SiteLanches.Repositories.RepositoriesInterfaces;
using SiteLanches.ViewModels;
using System.Linq;

namespace SiteLanches.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(ILancheRepository lancheRepository, CarrinhoCompra carrinhoCompra)
        {
            _lancheRepository = lancheRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItems();
            _carrinhoCompra.CarrinhoCompraItens = itens;

            var carrinhoCompraViewModel = new CarrinhoCompraViewModel()
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
            };

            return View(carrinhoCompraViewModel);
        }

        public RedirectToActionResult AdicionarItemNoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault(p => p.LancheId == lancheId);
            if (lancheSelecionado != null)
                _carrinhoCompra.AdicionarAoCarrinho(lancheSelecionado);

            return RedirectToAction("Index");
        }

        public IActionResult RemoverItemDoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault(p => p.LancheId == lancheId);
            if (lancheSelecionado != null)
                _carrinhoCompra.RemoverDoCarrinho(lancheSelecionado);

            return RedirectToAction("Index");
        }
    }
}

SiteLanches/Controllers/LancheController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SiteLanches.Models;
using SiteLanches.Repositories.RepositoriesInterfaces;
using SiteLanches.ViewModels;

namespace SiteLanches.Controllers
{
    public class LancheController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        private readonly ICategoriaRepository _categoriaRepository;

        public LancheController(ILancheRepository lancheRepository, ICategoriaRepository categoriaRepository)
        {
            _lancheRepository = lancheRepository;
            _categoriaRepository = categoriaRepository;
        }

        public IActionResult List(string categoria)
        {
            IEnumerable<Lanche> lanches;
            string categoriaAtual;

            if(string.IsNullOrEmpty(categoria))
            {
                lanches = _lancheRepository.Lanches.OrderBy(l => l.LancheId);
                categoriaAtual = "Todos os lanches";
            }
            else
            {
                lanches = _lancheRepository.Lanches.Where(l => string.Equals(l.Categoria.Nome, categoria, StringComparison.OrdinalIgnoreCase)).OrderBy(l => l.Nome);
                categoriaAtual = categoria;
            }

            var lanchesListiewModel = new LancheListViewModel
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual.ToUpper()
            };
            return View(lanchesListiewModel);
        }
        
        public  IActionResult Details(int lancheId)
        {
            var lanche = _lancheRepository.Lanches.FirstOrDefault(l => l.LancheId == lancheId);
            
            return View(lanche);
        }
    }
}

SiteLanches/Views/Lanche/Details.cshtml
@model Lanche

<div class="container marginTop">
    <div class="row">
        <div class="card border-0">
            <div class="text-center view overlay hm-white-slight">
                <img src="@Model.ImagemUrl" class="img-fluid" alt="">
                <a href="#">
                    <div class="mask waves-effect waves-light"></div>
                </a>
            </div>
            <div class="card-block">
                <!--Title-->
                <h2 class="card-title">@Model.Nome</h2>
                <!--Text-->
                <p class="card-text"><h5>@Model.DescricaoLonga</h5>
                <p class="btn btn-group align-content-lg-end" >
                    <a asp-controller="Lanche" asp-action="List" class="btn btn-outline-info">Ver todos os lanches</a>
                    <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-lancheId="@Model.LancheId">
                        Adicionar @Model.Nome ao carrinho
                    </a>
                </p>
            </div>
        </div>
    </div>
</div>

SiteLanches/Views/Lanche/List.cshtml
@model LancheListViewModel

<h2>@Model.CategoriaAtual</h2>

<div class="row">
    @foreach (var lanche in Model.Lanches)
    {
        <partial name="_LanchesResumo" for="@lanche" />
    }
</div>