SiteLanches/Controllers/CarrinhoCompraController.cs
using Microsoft.AspNetCore.Mvc;
using SiteLanches.Models;
using SiteLanches.Repositories.RepositoriesInterfaces;
using SiteLanches.ViewModels;
using System.Linq;

namespace SiteLanches.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(ILancheRepository lancheRepository, CarrinhoCompra carrinhoCompra)
        {
            _lancheRepository = lancheRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItems();
            _carrinhoCompra.CarrinhoCompraItens = itens;

            var carrinhoCompraViewModel = new CarrinhoCompraViewModel()
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
            };

            return View(carrinhoCompraViewModel);
        }

        public RedirectToActionResult AdicionarItemNoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault(p => p.LancheId == lancheId);
            if (lancheSelecionado != null)
                _carrinhoCompra.AdicionarAoCarrinho(lancheSelecionado);

            return RedirectToAction("Index");
        }

        public IActionResult RemoverItemDoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault(p => p.LancheId == lancheId);
            if (lancheSelecionado != null)
                _carrinhoCompra.RemoverDoCarrinho(lancheSelecionado);

            return RedirectToAction("Index");
        }
    }
}

SiteLanches/Controllers/ContatoController.cs
using Microsoft.AspNetCore.Mvc;

namespace SiteLanches.Controllers
{
    public class ContatoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SiteLanches/Views/Shared/_Carousel.cshtml
<div id="carouselLanches" class="carousel slide marginTop1" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselLanches" data-slide-to="0" class="active"></li>
        <li data-target="#carouselLanches" data-slide-to="1"></li>
        <li data-target="#carouselLanches" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/images/carousel11.jpg" class="d-block w-100" alt="Lanche">
        </div>
        <div class="carousel-item">
            <img src="~/images/carousel12.jpg" class="d-block w-100" alt="Lanche">
        </div>
        <div class="carousel-item">
            <img src="~/images/carousel13.jpg" class="d-block w-100" alt="Lanche">
        </div>
    </div>
    <a class="left carousel-control" href="#carouselLanches" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carouselLanches" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>

SiteLanches/Views/Shared/_LanchesResumo.cshtml
@model Lanche

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="img-fluid">
        <img src="@Model.ImagemUrl" style="height:200px;width:200px" class="img-rounded" alt=""/>
    </div>
    <div class="caption">
        <h3 class="formPullRightButton"> @Model.Preco.ToString("c")</h3>
        <h3>
            <a asp-controller="Lanche" asp-action="Details" asp-route-lancheId="@Model.LancheId">@Model.Nome</a>
        </h3>
        <p>@Model.DescricaoCurta</p>
    </div>
    <div class="text-right">
        <p class="button">
            <a class="btn btn-primary" asp-controller="CarrinhoCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-lancheId="@Model.LancheId">
                Incluir no Carrinho <b class="bi-cart"></b>
            </a>
        </p>
    </div>
</div>

SiteLanches/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SiteLanches</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SiteLanches</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Contato</a>
                        </li>
                        @await  Component.InvokeAsync("CategoriaMenu")
                        @await Component.InvokeAsync("CarrinhoCompraResumo")
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>